### ISSUE TITLE
Contact and credit

### ISSUE THREAD

**Issue by martinlanton** [hannesdelbeke/hannesdelbeke#1]
Hi,

Sorry for the issue here, but I couldn't find any other way to contact you. I'd like to credit you on linkedin for helping with the script editor highlighter, but I am not 100% sure that the linkedin profile I found is yours.

If you'd like to be credited, you can send me your linkedin profile at : lantonmartin@gmail.com

Again, thanks for the help!

Cheers!

**Comment by hannesdelbeke** [comment]
feel free to credit my github https://github.com/hannesdelbeke :)
